name: Feature Request
description: Suggest a new feature to be added.
labels:
  - quality of life
  - suggestion
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem were you having?
      description: Only fill out if your suggestion is related to a problem.
      placeholder: 'Example: I don''t like dark theme.'
  - type: textarea
    id: solution
    attributes:
      label: What solution would you like?
      description: Provide as much detail as possible.
      placeholder: 'Example: Add a switch to change to light theme.'
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: What alternatives have you considered?
      description: Provide as much detail as possible. Do not respond with "don't do this."
      placeholder: 'Example: Use the user''s preference for theme.'
    validations:
      required: true
  - type: textarea
    id: pros-and-cons
    attributes:
      label: What are some pros and cons of doing this?
      description: Provide as much detail as possible.
      placeholder: >
        #### Pros:


        - Some users might prefer light theme

        - Makes it easier to see contrast

        - Easy to implement


        #### Cons:


        - Most users prefer dark theme

        - Could get messy with the code or web layout
        
        - Low demand
      value: >
        #### Pros:


        - 
        
        - 
        
        - 

        
        #### Cons:

        
        - 
        
        - 
        
        - 
    validations:
      required: true
  - type: dropdown
    id: site-page
    attributes:
      label: What page is this for?
      description: Leave blank if none apply.
      multiple: true
      options:
        - Main Site
        - Blog
        - Projects
        - Twelve of Code
        - Repository
  - type: markdown
    attributes:
      value: >-
        [Code of Conduct](https://github.com/twelve-of-code-official/.github/blob/main/CODE_OF_CONDUCT.md)
        applies.
